import { nanoid } from "nanoid";
import type { NextPage } from "next";
import Head from "next/head";
import { useRouter } from "next/router";

const Home: NextPage = () => {
  const router = useRouter()

  const createRoom = () => {
    const id = nanoid()

    router.push(`rooms/${id}`)
  }

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="container mx-auto flex min-h-screen flex-col items-center justify-center p-4 gap-5">
        {/* <h1>{hello?.data?.greeting}</h1> */}
        <button onClick={createRoom} className='py-1 px-5 bg-slate-400 text-white rounded-lg transition-all hover:scale-105'>Create chat room</button>
      </main>
    </>
  );
};

export default Home